import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'
import { HomePage } from '../../src/components/Home-Page'

const inter = Inter({ subsets: ['latin'] })

interface eventCategoryInterface {
  id: string;
  title: string;
  description: string;
  image: string;
}

const EventsPage=({data}:{data:eventCategoryInterface[]})=> {
  return (
    <>
    <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
      <main className={styles.main}>
        
        <HomePage data={data} />
        
      </main>
    </>
  )
}

export default EventsPage;

export async function getServerSideProps(){
  const data=await import('../../data/data.json');
  const categories=data.events_categories;
  return {
    props:{
      data:categories,
    }
  }
}




